server:
  port: 8080

logging:
  level:
    org.springframework.ai.mcp: DEBUG
    io.modelcontextprotocol: DEBUG

spring:
  config:
    import: optional:file:.env[.properties]
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL}
      chat:
        options:
          model: ${OPENAI_MODEL}
          temperature: 1
    mcp:
      client:
        enabled: true
        type: SYNC            # 또는 ASYNC
        request-timeout: 30s
        stdio:
          connections:
            # DuckDuckGo MCP
            duck:
              command: ${MCP_DDG_CMD}
              args: []
            # DartPoint MCP
            dartpoint:
              command: "C:/Program Files/nodejs/npx.cmd"
              args:
                - mcp-remote
                - https://dartpoint.ai/mcp-sse/mcp
                - --header
                - "DARTPOINT-API-KEY:${DARTPOINT_API_KEY}"
