spring:
  ai:
    ollama:
      base-url: http://localhost:11434   # ?? ?? IP
      chat:
        options:
          model: qwen2.5:3b             # ??? pull? ???
      init:
        pull-model-strategy: never       # ?? ? ?? pull ???(??)
